services:
  applicationdb:
    container_name: applicationdb
    environment:
      - ACCEPT_EULA=Y   
      - SA_PASSWORD=T!9m@Q4z
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: messagebroker
    hostname: premierhack-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  hackathon.premiersoft.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__db_connection=Server=applicationdb;Database=applicationdb;User Id=sa;Password=T!9m@Q4z;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://premierhack-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - applicationdb
      - messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro